name: "Auto Sync Fork"

on:
  schedule:
    - cron: "0 16 * * *"  # scheduled at 00:00 (UTC+8) everyday
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Fork sync
        uses: tgymnich/fork-sync@v1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: y1ndan
          base: master
          head: master
